version: '3'
services:
  research:
    build:
      context: ./research
      dockerfile: Dockerfile
    volumes:
      - "./research/notebooks/:/notebooks/"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888/tcp"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - ./persisted-db:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/csvs/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: psql # postgres://root:psql@db:5432/<db_name>
    ports: 
      - "5432:5432/tcp"